# -*- coding: utf-8 -*-
"""Central Visual V629 — redesign geral.

Não altera a lógica do Discord, Procurados, Boletins, Perícias ou Fotos.
Apenas troca a apresentação web por uma interface única, responsiva e mais
organizada, preservando as rotas já existentes da V628.
"""
from __future__ import annotations

from typing import Any
import html
import re
from datetime import datetime

import central_visual_v628 as v628
import central_discord_v613 as base
import central_procurados_v625 as v625
import central_procurados_v622 as v622

# Referências das versões anteriores permanecem intactas.

NEW_CSS = r'''
:root{--bg:#04080d;--panel:#08111b;--panel2:#0b1723;--line:#1a3045;--line2:#254863;--blue:#2e78b8;--blue2:#67b7f4;--gold:#dfb95d;--gold2:#9a701d;--green:#42d297;--red:#f06a73;--text:#edf3f8;--muted:#71869a}
*{box-sizing:border-box}html,body{margin:0;padding:0;min-height:100%;font-family:Inter,Segoe UI,Arial,sans-serif;background:radial-gradient(circle at 90% -10%,#153d61 0,#081421 28%,#04080d 68%);color:var(--text)}body:after{content:'';position:fixed;inset:0;pointer-events:none;background:linear-gradient(115deg,transparent 0 66%,#1d5f9510 66% 67%,transparent 67%),linear-gradient(0deg,#0005,#0000)}a{color:inherit;text-decoration:none}
.app{min-height:100vh;display:grid;grid-template-columns:235px minmax(0,1fr)}.side{position:sticky;top:0;height:100vh;padding:16px 12px;border-right:1px solid var(--line);background:linear-gradient(180deg,#07111b,#04090f);z-index:10}.brand{display:flex!important;align-items:center!important;gap:10px!important;padding:6px 7px 16px!important;border-bottom:1px solid var(--line)!important}.brand img{width:48px!important;height:48px!important;object-fit:contain!important;background:transparent!important;filter:drop-shadow(0 8px 18px #0009)!important}.brand b{font-size:14px!important;letter-spacing:2px!important}.brand small{display:block!important;color:var(--gold)!important;font-size:7px!important;letter-spacing:2px!important;margin-top:4px!important}.nav{display:grid;gap:6px;margin-top:16px}.nav a{padding:12px 11px;border:1px solid transparent;border-radius:10px;color:#8096aa;font-size:8px;font-weight:900;letter-spacing:1px}.nav a:hover,.nav a.active{background:#0d2235;border-color:#254861;color:#f0c968}.side-note,.sidebar-foot{position:absolute!important;left:12px!important;right:12px!important;bottom:14px!important;margin:0!important;padding:11px!important;border:1px solid var(--line)!important;border-radius:11px!important;color:#5f7488!important;background:#06101a!important;font-size:7px!important;line-height:1.8!important}
.main{min-width:0!important;padding:18px 22px 38px!important}.top{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:15px!important;padding-bottom:13px!important;border-bottom:1px solid var(--line)!important}.pcpt-title{font-size:10px!important;font-weight:950!important;letter-spacing:1.8px!important}.pcpt-title span{display:block!important;margin-top:4px!important;color:#60778d!important;font-size:7px!important;letter-spacing:1.2px!important}.operator{font-size:7px!important;color:#8195a8!important}.online{width:7px!important;height:7px!important;border-radius:50%!important;background:var(--green)!important;box-shadow:0 0 12px #42d297!important}
.hero{margin-top:16px!important;padding:22px!important;border:1px solid var(--line2)!important;border-radius:16px!important;background:linear-gradient(125deg,#0a1a29,#08131f 58%,#07111b)!important;box-shadow:0 20px 55px #0005,inset 0 0 60px #1c5d8c10!important}.hero:after{right:-160px!important;top:-190px!important;width:430px!important;height:430px!important;border-color:#2f78b829!important;box-shadow:0 0 0 40px #2f78b80a,0 0 0 80px #2f78b805!important}.eyebrow{font-size:7px!important;letter-spacing:2.5px!important;color:var(--blue2)!important}.hero h1{font-size:31px!important;letter-spacing:1.2px!important;margin:8px 0 6px!important}.hero p{font-size:9px!important;max-width:760px!important;color:#73899d!important;line-height:1.55!important}
.stats{gap:9px!important;margin-top:11px!important}.stat{padding:13px!important;border-radius:11px!important;background:linear-gradient(145deg,#091520,#07101a)!important;border-color:var(--line)!important}.stat span{font-size:6px!important;letter-spacing:1.4px!important;color:#5f768c!important}.stat b{font-size:24px!important;margin-top:6px!important}.stat.blue b{color:#5fb0ed!important}.stat.gold b{color:var(--gold)!important}.stat.red b{color:var(--red)!important}
.wanted,.section{margin-top:13px!important;border:1px solid var(--line)!important;border-radius:14px!important;background:#050c13!important;overflow:hidden!important;box-shadow:0 12px 30px #0004!important}.wanted-head,.section-head{padding:13px 15px!important;border-bottom:1px solid #14273a!important;background:#07111b!important}.wanted-head b,.section-head b{font-size:9px!important;letter-spacing:1.3px!important}.wanted-head span,.section-head span{font-size:7px!important;color:#5f768c!important}.grid{padding:10px!important;gap:9px!important}.card{border-color:#193049!important;border-radius:11px!important;background:linear-gradient(155deg,#0b1824,#071018)!important}.photo{height:150px!important;background:#05090e!important}.photo img{object-fit:cover!important}.card-body{padding:10px!important}.tag{font-size:6px!important;padding:4px 6px!important}.card h3{font-size:11px!important;margin:8px 0 4px!important}.meta{font-size:7px!important;color:#75899b!important;line-height:1.7!important}.details{margin-top:8px!important;padding:8px!important;font-size:7px!important;border-color:#234561!important;color:#83b9e5!important}
.access{margin-top:12px!important;padding:14px 16px!important;border-color:#7f5f20!important;background:linear-gradient(110deg,#151209,#0b1015)!important;border-radius:12px!important}.access strong{font-size:10px!important;color:#efcf73!important}.access span{font-size:7px!important;color:#72684f!important}.access-btn{padding:10px 14px!important;font-size:8px!important;border-radius:8px!important;background:linear-gradient(135deg,#efd073,#9d7019)!important}
.module-grid{gap:10px!important;margin-top:12px!important}.module{padding:16px!important;border:1px solid var(--line)!important;border-radius:12px!important;background:linear-gradient(145deg,#0a1722,#071019)!important}.module h3{font-size:11px!important;margin:8px 0 5px!important}.module p{font-size:8px!important;color:#71859a!important}.module a{padding:9px!important;margin-top:11px!important;border-radius:8px!important;background:#0e2337!important;color:#e0bd63!important;font-size:7px!important}
/* Boletins / Perícias */.panel-wrap{margin-top:16px!important}.panel-head{padding:19px!important;border-color:var(--line2)!important;border-radius:14px 14px 0 0!important;background:linear-gradient(120deg,#0b1b2a,#07121c)!important}.panel-kicker{font-size:7px!important;letter-spacing:2px!important}.panel-head h1{font-size:24px!important;margin:7px 0 4px!important}.panel-head p{font-size:9px!important}.panel-counter b{font-size:27px!important;color:var(--gold)!important}.panel-toolbar{padding:10px!important;background:#06101a!important;border-color:var(--line)!important}.panel-search,.panel-filter{height:40px!important;background:#081522!important;border-color:#203b53!important;font-size:9px!important}.panel-body{background:#050c13!important;border-color:var(--line)!important}.panel-table-head{padding:9px 13px!important;background:#08131e!important;grid-template-columns:100px minmax(0,1.7fr) minmax(0,1fr) 145px 105px!important;font-size:6px!important}.case-row{padding:12px 13px!important;grid-template-columns:100px minmax(0,1.7fr) minmax(0,1fr) 145px 105px!important;background:#071019!important;border-color:#12283a!important}.case-no{font-size:8px!important;color:var(--gold)!important}.case-title b{font-size:9px!important}.case-title span{font-size:7px!important}.case-info{font-size:7px!important}.case-info strong{font-size:5px!important}.case-time{font-size:7px!important}.case-status{min-height:27px!important;font-size:6px!important}.case-open{font-size:6px!important;padding:8px!important}.panel-foot{padding:8px 11px!important;font-size:6px!important}
/* Fotos */.photo-manager{margin-top:14px}.photo-hero{padding:19px;border:1px solid var(--line2);border-radius:14px;background:linear-gradient(120deg,#0b1b29,#07111b)}.photo-hero h1{font-size:27px;margin:7px 0 4px}.photo-hero p{font-size:9px;color:#70869a;max-width:700px}.upload-zone{margin-top:13px;padding:13px;border:1px dashed #355878;border-radius:11px;background:#07131e}.upload-zone b{display:block;font-size:8px;color:#d6b65d;margin-bottom:8px}.upload-zone input{width:100%;font-size:9px;color:#9db0bf}.upload-btn{margin-top:10px;border:0;border-radius:8px;padding:10px 14px;background:linear-gradient(135deg,#e9cb6c,#a47119);font-size:8px;font-weight:900;color:#070a0d;cursor:pointer}.photo-list{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:11px}.photo-item{border:1px solid var(--line);border-radius:11px;overflow:hidden;background:#07111a}.photo-item img{width:100%;height:150px;display:block;object-fit:cover;cursor:pointer}.photo-item .pi{padding:9px}.photo-item small{font-size:7px;color:#c6d1da}.stable-link{font-size:6px!important;color:#5d778d!important;word-break:break-all!important;margin-top:5px}.copy-link{margin-top:8px;width:100%;padding:8px;border:1px solid #294862;border-radius:7px;background:#0c1c2b;color:#8ebde4;font-size:6px;font-weight:900;cursor:pointer}
/* Login */body:has(.auth){background:radial-gradient(circle at 50% 0,#173d64 0,#091522 34%,#04080d 72%)!important}.auth{width:min(560px,calc(100% - 28px))!important;padding:31px!important;border-radius:20px!important;border:1px solid #31516f!important;background:linear-gradient(155deg,#0f1c2aef,#07101af5)!important;box-shadow:0 30px 90px #000c!important}.auth .logo{width:104px!important;height:104px!important;object-fit:contain!important;background:transparent!important;filter:drop-shadow(0 12px 22px #0009)!important}.auth h1{font-size:25px!important}.pcpt{font-size:9px!important;letter-spacing:2px!important}.sub{font-size:10px!important}.form label{font-size:7px!important}.form input{height:46px!important;border-radius:10px!important;background:#081521!important;border-color:#203d57!important;font-size:13px!important}.primary{height:48px!important;border-radius:10px!important;font-size:9px!important}.first,.secure{font-size:7px!important}
@media(max-width:1000px){.app{grid-template-columns:205px minmax(0,1fr)}.grid{grid-template-columns:repeat(3,1fr)}.photo-list{grid-template-columns:repeat(3,1fr)}}
@media(max-width:760px){.app{display:block}.side{display:none}.main{padding:11px 11px 28px!important}.grid{grid-template-columns:repeat(2,1fr)}.stats{grid-template-columns:repeat(2,1fr)}.module-grid{grid-template-columns:repeat(2,1fr)}.panel-table-head{display:none}.case-row{display:grid;grid-template-columns:1fr auto!important;gap:8px!important}.case-no{grid-column:1/-1}.case-title{grid-column:1}.case-info{grid-column:1}.case-status{grid-column:2;grid-row:2/4;min-width:92px}.case-time{display:none}.case-open{grid-column:1/-1}.photo-list{grid-template-columns:repeat(2,1fr)}}
@media(max-width:500px){.grid,.photo-list,.module-grid{grid-template-columns:1fr}.top{align-items:flex-start}.operator{font-size:6px}.hero h1{font-size:25px}.photo-list{padding:9px}.photo-item img{height:210px}.auth{padding:24px 19px!important}.auth .logo{width:88px!important;height:88px!important}}
'''


def apply():
    # Substitui o CSS sem tocar na lógica existente.
    base.APP_CSS = NEW_CSS
    try:
        base.AUTH_CSS = NEW_CSS + base.AUTH_CSS
    except Exception:
        pass

    # Dashboard já existente continua com a mesma fonte de dados.
    # Procurados da V625 mantém consulta completa; o CSS novo reorganiza tudo.
    return True


def install(bot_module: Any):
    apply()
    # V628 mantém a inicialização e os patches das rotas já funcionais.
    return v628.install(bot_module)
